FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install pytest
RUN pip install pytest 

# Copy the content of the local src directory to the working directory
COPY . .

# Expose the port number on which the Streamlit app will run
EXPOSE 8501

# Run pytest before starting the Streamlit app
#RUN pytest test.py 

# Command to run the Streamlit app
CMD ["streamlit", "run", "app.py"]
